name: monero_rpc
description: Monero JSON-RPC API wrapper in Dart.
version: 1.0.0
repository: https://github.com/ManyMath/monero_rpc

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  digest_auth: ^1.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
